### ISSUE TITLE
Webservice não encontrado

### ISSUE THREAD

**Issue by rodrigorahman** [alura-cursos/argentum-web#19]
Não existe mais o webservice http://argentumws.caelum.com.br/negociacoes ele está apresentando erro. sendo assim a aplicação não sobe mais.

**Comment by leandroramos** [comment]
Estou parado no curso por causa dessa aplicação.

**Comment by soeirosantos** [comment]
Oi Pessoal, tudo bom? Eu não tenho acompanhado o curso muito de perto, mas como estou seguindo esse repositório recebi as notificações do github. Vou ver se consigo ajudar com isso... 

Abs!

**Comment by soeirosantos** [comment]
Eu mandei um e-mail pedindo pro pessoal dar uma olhada no serviço que está fora.

Nesse meio tempo, se vocês quiserem avançar vocês podem fazer o seguinte: 

1) Baixa o webservice de negociações aqui https://github.com/alura-cursos/argentum-web/blob/master/argentumws.war
2) Faz deploy dele localmente no [Tomcat 7](http://mirrors.ocf.berkeley.edu/apache/tomcat/tomcat-7/v7.0.91/bin/apache-tomcat-7.0.91.zip)
3) Substitui o [endereço do serviço](https://github.com/alura-cursos/argentum-web/blob/master/src/main/java/br/com/caelum/argentum/ws/ClienteWebService.java#L14) por http://localhost:8080/argentumws/negociacoes 

Isso deve ajudar pra vocês não ficarem parados.

Abs!

**Comment by steppat** [comment]
Pessoal, estamos restaurando o DNS mas nesse meio tempo já podem usar a URL:

https://argentumws-spring.herokuapp.com/negociacoes

**Comment by steppat** [comment]
Pessoal, já voltou:

http://argentumws.caelum.com.br/negociacoes

**Comment by leandroramos** [comment]
Tenho uma dúvida: A aplicação roda no Tomcat8? Se não rodar, vou procurar alguma outra, porque acredito que possa usar outra para seguir o curso de Jenkins.
